name: CI

on:
  release:
    types: [prereleased, published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Echo when released
        run: echo foo
